---
title: "Denitrification analysis"
author: JB
date: September 2022
project: EMBRACE
output: html_notebook
editor_options: 
  chunk_output_type: console
---

Session Info
R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.6
```{r}
sessionInfo()
packageVersion("tidyverse") # ‘1.3.1’
packageVersion("here")      # ‘1.0.1’
```

# Install and load packages
```{r}
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("here")) install.packages("here")
if (!require("car")) install.packages("car")
if (!require("emmeans")) install.packages("emmeans")
if (!require("ggpubr")) install.packages("ggpubr")
```

# Import data
```{r}
Den <- read.table("Denitr_graph.txt", header=T)
```

# Check data
```{r}
view(Den) 
names(Den)
str(Den)
```

# Reorganize table
```{r}
Den %>% 
  group_by(Site, Incubation, Treatment) %>%
  summarise(n = n()) %>%  view()

Den <- Den %>% 
  mutate(
    Site = factor (x = Site, levels = c("Ambient", "Vent")),
    Incubation = factor (x = Incubation, levels = c("light", "dark")),
    Treatment = factor(x = Treatment, levels = c("Y", "N")),
  ) %>% 
  view()
str(Den)
```


# Statistical Analysis
# 29N and 30N production rates per h

# 29N
```{r}
# only in +Epi treatments
Den_Epi <- Den %>% 
  filter(Treatment=="Y") %>% 
  view()
```

# Outlier, normality & variance check
```{r}
ggplot(data = Den_Epi, aes(x = Site, y = rate_29N_pm_h, color = Incubation))+
  geom_boxplot(fill = NA, coef = 3, 
               outlier.shape = "?", 
               outlier.colour = "black", 
               outlier.size = 3)+
  geom_point(position = position_jitterdodge(), alpha = 0.5)+
  theme_bw()
# no outliers

# test normal distribution 
qqnorm(Den_Epi$rate_29N_pm_h)
qqline(Den_Epi$rate_29N_pm_h)
hist(Den_Epi$rate_29N_pm_h)

# Shapiro test for normal distribution
shapiro.test(Den_Epi$rate_29N_pm_h)
# p-value = 0.009652 -->  not normally distributed, still okay for Anova 

# Levene's Test for Homogeneity of Variances
leveneTest(Den_Epi$rate_29N_pm_h~ Site*Incubation, data = Den_Epi)
#p-value = 0.3554 --> variances are not different for different sites and treatments
```

# Anova
```{r}
M<-lm(Den_Epi$rate_29N_pm_h~Site*Incubation, data=Den_Epi)
Anova(M)
# interaction not significant --> reduce model
M<-lm(Den_Epi$rate_29N_pm_h~Site+Incubation, data=Den_Epi)
Anova(M)
summary(M)

# Anova Table (Type II tests)

# Response: Den_Epi$rate_29N_pm_h
#               Sum Sq Df F value   Pr(>F)   
# Site       0.031835  1 10.8182 0.005869 **
# Incubation 0.002268  1  0.7707 0.395943   
# Residuals  0.038256 13

#Adjusted R-squared:   0.39 

par(mfrow=c(2,2))
plot(M)
# normality and homogeneity are met

emm = emmeans(M, specs = pairwise ~ Site:Incubation)
emm
```

# plot results 
```{r}

p3_raw<-ggplot(data = Den_Epi, aes(x = Site, y = rate_29N_pm_h, color=Incubation))+
  geom_boxplot(fill = NA, coef = 3)+
  geom_point(position = position_jitterdodge(), alpha = 0.5)+
  theme_classic()+
  scale_color_manual(values = c("#6F9CDE", "darkblue"), labels=c("light", "dark"))+ 
  theme(legend.title = element_blank())+
  labs(x="pH", y=expression({}^29*N[2]~production~rate~(pmol~N~cm^-2~h^-1)))+
  scale_y_continuous(limits=c(-11,30), breaks=c(-10,-5,0,5,10,15,20,25,30))
p3_raw
```

# 30N
```{r}
# only in +Epi treatments
Den_Epi <- Den %>% 
  filter(Treatment=="Y") %>% 
  view()
```

# Outlier, normality & variance check
```{r}
ggplot(data = Den_Epi, aes(x = Site, y = rate_30N_pm_h, color = Incubation))+
  geom_boxplot(fill = NA, coef = 3, 
               outlier.shape = "?", 
               outlier.colour = "black", 
               outlier.size = 3)+
  geom_point(position = position_jitterdodge(), alpha = 0.5)+
  theme_bw()
# no outliers

# test normal distribution 
qqnorm(Den_Epi$rate_30N_pm_h)
qqline(Den_Epi$rate_30N_pm_h)
hist(Den_Epi$rate_30N_pm_h)

# Shapiro test for normal distribution
shapiro.test(Den_Epi$rate_30N_pm_h)
# p-value = 0.0434 --> not normally distributed, still okay for Anova

# Levene's Test for Homogeneity of Variances
leveneTest(Den_Epi$rate_30N_pm_h~ Site*Incubation, data = Den_Epi)
#p-value = 0.8171 --> variances are not different for different sites and treatments
```

# Anova
```{r}
M<-lm(Den_Epi$rate_30N_pm_h~Site+Incubation, data=Den_Epi)
Anova(M)
summary(M)

# Anova Table (Type II tests)

# Response: Den_Epi$rate_30N_pm_h
#            Sum Sq Df F value  Pr(>F)  
# Site       304.85  1  5.9518 0.02979 *
# Incubation 428.46  1  8.3651 0.01259 *
# Residuals  665.85 13

# Adjusted R-squared:  0.4509 

par(mfrow=c(2,2))
plot(M)
# normality and homogeneity are met

emm = emmeans(M, specs = pairwise ~ Site:Incubation)
emm
```

# plot results 
```{r}

p4_raw<-ggplot(data = Den_Epi, aes(x = Site, y = rate_30N_pm_h, color=Incubation))+
  geom_boxplot(fill = NA, coef = 3)+
  geom_point(position = position_jitterdodge(), alpha = 0.5)+
  theme_classic()+
  scale_color_manual(values = c("#6F9CDE", "darkblue"), labels=c("light", "dark"))+ 
  theme(legend.title = element_blank())+
  labs(x="pH", y=expression({}^30*N[2]~production~rate~(pmol~N~cm^-2~h^-1)))+
  scale_y_continuous(limits=c(-11,30), breaks=c(-10,-5,0,5,10,15,20,25,30))
p4_raw
```


create panel
```{r}
panel1<-ggarrange(p1_raw,p2_raw,p3_raw,p4_raw, 
                labels = c("a", "b", "c", "d"),
                ncol = 2, nrow = 2, align = "hv",
                font.label = list(size = 14),
                common.legend=T,
                legend="right")
panel1

ggsave(panel1, filename = ("N_transformations.png"), dpi = 300, units = "cm", width = 20, height = 18)
```








