---
title: "Denitrification analysis"
author: JB
date: September 2022
project: EMBRACE
output: html_notebook
---

Session Info
R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.6
```{r}
sessionInfo()
packageVersion("tidyverse") # ‘1.3.1’
packageVersion("here")      # ‘1.0.1’
```

# Install and load packages
```{r}
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("here")) install.packages("here")
if (!require("car")) install.packages("car")
if (!require("emmeans")) install.packages("emmeans")
if (!require("ggpubr")) install.packages("ggpubr")
```

# Create "output" folder
```{r}
here()
dir.create(here("output"))
```

# Import data
```{r}
Den <- read.table(here("Google Drive", "Marine Symbiomes Group folder","EMBRACE" ,"MS Posidonia N cycling", "Biogeochemistry","Data","Raw data", "Denitr_graph.txt"), header=T)
```

# Check data
```{r}
view(Den) 
names(Den)
str(Den)
```

# Reorganize table
```{r}
Den %>% 
  group_by(Site, Incubation, Treatment) %>%
  summarise(n = n()) %>%  view()

Den <- Den %>% 
  mutate(
    Site = factor (x = Site, levels = c("Ambient", "Vent")),
    Incubation = factor (x = Incubation, levels = c("light", "dark")),
    Treatment = factor(x = Treatment, levels = c("Y", "N")),
  ) %>% 
  view()
```


# Statistical Analysis
# 29N and 30N production rates

# 29N
```{r}
# only in +Epi treatments
Den_Epi <- Den %>% 
  filter(Treatment=="Y") %>% 
  view()
```

# Outlier, normality & variance check
```{r}
ggplot(data = Den_Epi, aes(x = Site, y = rate_29N, color = Incubation))+
  geom_boxplot(fill = NA, coef = 3, 
               outlier.shape = "?", 
               outlier.colour = "black", 
               outlier.size = 3)+
  geom_point(position = position_jitterdodge(), alpha = 0.5)+
  theme_bw()
# no outliers

# test normal distribution 
qqnorm(Den_Epi$rate_29N)
qqline(Den_Epi$rate_29N)
hist(Den_Epi$rate_29N)

# Shapiro test for normal distribution
shapiro.test(Den_Epi$rate_29N)
# p-value = 0.009652 -->  not normally distributed, still okay for Anova 

# Levene's Test for Homogeneity of Variances
leveneTest(Den_Epi$rate_29N~ Site*Incubation, data = Den_Epi)
#p-value = 0.3554 --> variances are not different for different sites and treatments
```

# Anova
```{r}
M<-lm(Den_Epi$rate_29N~Site*Incubation, data=Den_Epi)
Anova(M)
# interaction not significant --> reduce model
M<-lm(Den_Epi$rate_29N~Site+Incubation, data=Den_Epi)
Anova(M)
summary(M)

# Anova Table (Type II tests)

# Response: Den_Epi$rate_29N
#               Sum Sq Df F value   Pr(>F)   
# Site       0.031835  1 10.8182 0.005869 **
# Incubation 0.002268  1  0.7707 0.395943   
# Residuals  0.038256 13

par(mfrow=c(2,2))
plot(M)
# normality and homogeneity are met

emm = emmeans(M, specs = pairwise ~ Site:Incubation)
emm
```

# plot results from model
```{r}
emm<-data.frame(emmeans(M,~Site+Incubation))%>% 
  summarise(Site=Site,Incubation=Incubation,emmean=emmean)%>% 
  view()

sum <- Den_Epi%>% 
  group_by(Incubation,Site)%>% 
  summarise(sd=sd(rate_29N),
            n = n(),
            se=sd/sqrt(n))%>% 
  view()

final <- cbind(emm[c("Site","Incubation","emmean")], sum[c("sd", "se")])%>%
  summarise(Site=Site,
            Incubation=Incubation,            
            emmean=emmean,
            sd=sd,
            se=se)%>% 
  view()

p1<-ggplot(data = final, aes(x = Site, y = emmean, fill=Incubation))+
  geom_bar(position="dodge", stat="identity")+
  geom_errorbar(aes(Site,ymin=emmean-se, ymax=emmean+se),position=position_dodge(.9),width=0.2)+
  scale_fill_manual(values = c("lightblue", "darkblue"), labels=c("light", "dark"))+
  theme_classic()+
  theme(legend.title = element_blank())+
  labs(x="pH", y=expression({}^29*N[2]~production~rate~(nmol~N~cm^-2~d^-1)))+
  scale_y_continuous(limits=c(-0.11,0.55), breaks=c(-0.1,-0.05,0,0.05,0.10,0.15,0.20,0.25,0.3,0.35,0.4,0.45,0.5,0.55))
p1

ggsave(p1, filename = here( "output", "29N_production_rate.png"), dpi = 300, units = "cm", width = 15, height = 15)
```

# 30N
```{r}
# only in +Epi treatments
Den_Epi <- Den %>% 
  filter(Treatment=="Y") %>% 
  view()
```

# Outlier, normality & variance check
```{r}
ggplot(data = Den_Epi, aes(x = Site, y = rate_30N, color = Incubation))+
  geom_boxplot(fill = NA, coef = 3, 
               outlier.shape = "?", 
               outlier.colour = "black", 
               outlier.size = 3)+
  geom_point(position = position_jitterdodge(), alpha = 0.5)+
  theme_bw()
# no outliers

# test normal distribution 
qqnorm(Den_Epi$rate_30N)
qqline(Den_Epi$rate_30N)
hist(Den_Epi$rate_30N)

# Shapiro test for normal distribution
shapiro.test(Den_Epi$rate_30N)
# p-value = 0.0434 --> not normally distributed, still okay for Anova

# Levene's Test for Homogeneity of Variances
leveneTest(Den_Epi$rate_30N~ Site*Incubation, data = Den_Epi)
#p-value = 0.8171 --> variances are not different for different sites and treatments
```

# Anova
```{r}
M<-lm(Den_Epi$rate_30N~Site*Incubation, data=Den_Epi)
Anova(M)
summary(M)

# Anova Table (Type II tests)

# Response: Den_Epi$rate_30N
#                   Sum Sq Df F value    Pr(>F)    
# Site            0.17559  1  12.137 0.004514 **
# Incubation      0.24679  1  17.058 0.001395 **
# Site:Incubation 0.20992  1  14.510 0.002488 **
# Residuals       0.17361 12 

par(mfrow=c(2,2))
plot(M)
# normality and homogeneity are met

emm = emmeans(M, specs = pairwise ~ Site:Incubation)
emm
```

# plot results from model
```{r}
emm<-data.frame(emmeans(M,~Site*Incubation))%>% 
  summarise(Site=Site,Incubation=Incubation,emmean=emmean)%>% 
  view()

sum <- Den_Epi%>% 
  group_by(Incubation,Site)%>% 
  summarise(sd=sd(rate_30N),
            n = n(),
            se=sd/sqrt(n))%>% 
  view()

final <- cbind(emm[c("Site","Incubation","emmean")], sum[c("sd", "se")])%>%
  summarise(Site=Site,
            Incubation=Incubation,            
            emmean=emmean,
            sd=sd,
            se=se)%>% 
  view()

p2<-ggplot(data = final, aes(x = Site, y = emmean, fill=Incubation))+
  geom_bar(position="dodge", stat="identity")+
  geom_errorbar(aes(Site,ymin=emmean-se, ymax=emmean+se),position=position_dodge(.9),width=0.2)+
  scale_fill_manual(values = c("lightblue", "darkblue"), labels=c("light", "dark"))+
  theme_classic()+
  theme(legend.title = element_blank())+
  labs(x="pH", y=expression({}^30*N[2]~production~rate~(nmol~N~cm^-2~d^-1)))+
  scale_y_continuous(limits=c(-0.11,0.55), breaks=c(-0.1,-0.05,0,0.05,0.10,0.15,0.20,0.25,0.3,0.35,0.4,0.45,0.5,0.55))
p2

ggsave(p2, filename = here( "output", "30N_production_rate.png"), dpi = 300, units = "cm", width = 15, height = 15)
```
